addSbtPlugin("com.jsuereth"      % "sbt-pgp"            % "1.1.2")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"       % "1.1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"        % "1.0.10")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"       % "2.5")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"      % "1.6.1")
addSbtPlugin("org.scoverage"     % "sbt-coveralls"      % "1.2.7")
addSbtPlugin("com.twitter"       % "scrooge-sbt-plugin" % "19.10.0")
addSbtPlugin("com.47deg"         % "sbt-microsites"     % "0.9.7")
